var annotated =
[
    [ "CGAL", null, [
      [ "cpp11", "namespace_c_g_a_l_1_1cpp11.html", [
        [ "result_of", "struct_c_g_a_l_1_1cpp11_1_1result__of.html", "struct_c_g_a_l_1_1cpp11_1_1result__of" ]
      ] ],
      [ "cpp98", "namespace_c_g_a_l_1_1cpp98.html", [
        [ "binary_function", "struct_c_g_a_l_1_1cpp98_1_1binary__function.html", "struct_c_g_a_l_1_1cpp98_1_1binary__function" ],
        [ "unary_function", "struct_c_g_a_l_1_1cpp98_1_1unary__function.html", "struct_c_g_a_l_1_1cpp98_1_1unary__function" ]
      ] ],
      [ "Boolean_tag", "struct_c_g_a_l_1_1_boolean__tag.html", "struct_c_g_a_l_1_1_boolean__tag" ],
      [ "Cast_function_object", "struct_c_g_a_l_1_1_cast__function__object.html", "struct_c_g_a_l_1_1_cast__function__object" ],
      [ "CC_safe_handle", "class_c_g_a_l_1_1_c_c__safe__handle.html", "class_c_g_a_l_1_1_c_c__safe__handle" ],
      [ "Compact", "struct_c_g_a_l_1_1_compact.html", null ],
      [ "Compact_container", "class_c_g_a_l_1_1_compact__container.html", "class_c_g_a_l_1_1_compact__container" ],
      [ "Compact_container_base", "class_c_g_a_l_1_1_compact__container__base.html", "class_c_g_a_l_1_1_compact__container__base" ],
      [ "Compact_container_traits", "struct_c_g_a_l_1_1_compact__container__traits.html", "struct_c_g_a_l_1_1_compact__container__traits" ],
      [ "Compare_to_less", "class_c_g_a_l_1_1_compare__to__less.html", "class_c_g_a_l_1_1_compare__to__less" ],
      [ "Concurrent_compact_container", "class_c_g_a_l_1_1_concurrent__compact__container.html", "class_c_g_a_l_1_1_concurrent__compact__container" ],
      [ "Concurrent_compact_container_traits", "struct_c_g_a_l_1_1_concurrent__compact__container__traits.html", "struct_c_g_a_l_1_1_concurrent__compact__container__traits" ],
      [ "Const_oneset_iterator", "class_c_g_a_l_1_1_const__oneset__iterator.html", "class_c_g_a_l_1_1_const__oneset__iterator" ],
      [ "Construct_array", "struct_c_g_a_l_1_1_construct__array.html", "struct_c_g_a_l_1_1_construct__array" ],
      [ "Counting_iterator", "class_c_g_a_l_1_1_counting__iterator.html", "class_c_g_a_l_1_1_counting__iterator" ],
      [ "Creator_1", "class_c_g_a_l_1_1_creator__1.html", "class_c_g_a_l_1_1_creator__1" ],
      [ "Creator_2", "class_c_g_a_l_1_1_creator__2.html", "class_c_g_a_l_1_1_creator__2" ],
      [ "Creator_3", "class_c_g_a_l_1_1_creator__3.html", "class_c_g_a_l_1_1_creator__3" ],
      [ "Creator_4", "class_c_g_a_l_1_1_creator__4.html", "class_c_g_a_l_1_1_creator__4" ],
      [ "Creator_5", "class_c_g_a_l_1_1_creator__5.html", "class_c_g_a_l_1_1_creator__5" ],
      [ "Creator_uniform_2", "class_c_g_a_l_1_1_creator__uniform__2.html", "class_c_g_a_l_1_1_creator__uniform__2" ],
      [ "Creator_uniform_3", "class_c_g_a_l_1_1_creator__uniform__3.html", "class_c_g_a_l_1_1_creator__uniform__3" ],
      [ "Creator_uniform_4", "class_c_g_a_l_1_1_creator__uniform__4.html", "class_c_g_a_l_1_1_creator__uniform__4" ],
      [ "Creator_uniform_5", "class_c_g_a_l_1_1_creator__uniform__5.html", "class_c_g_a_l_1_1_creator__uniform__5" ],
      [ "Creator_uniform_6", "class_c_g_a_l_1_1_creator__uniform__6.html", "class_c_g_a_l_1_1_creator__uniform__6" ],
      [ "Creator_uniform_7", "class_c_g_a_l_1_1_creator__uniform__7.html", "class_c_g_a_l_1_1_creator__uniform__7" ],
      [ "Creator_uniform_8", "class_c_g_a_l_1_1_creator__uniform__8.html", "class_c_g_a_l_1_1_creator__uniform__8" ],
      [ "Creator_uniform_9", "class_c_g_a_l_1_1_creator__uniform__9.html", "class_c_g_a_l_1_1_creator__uniform__9" ],
      [ "Creator_uniform_d", "class_c_g_a_l_1_1_creator__uniform__d.html", "class_c_g_a_l_1_1_creator__uniform__d" ],
      [ "Default", "struct_c_g_a_l_1_1_default.html", "struct_c_g_a_l_1_1_default" ],
      [ "Dereference", "struct_c_g_a_l_1_1_dereference.html", "struct_c_g_a_l_1_1_dereference" ],
      [ "Dispatch_or_drop_output_iterator", "class_c_g_a_l_1_1_dispatch__or__drop__output__iterator.html", "class_c_g_a_l_1_1_dispatch__or__drop__output__iterator" ],
      [ "Dispatch_output_iterator", "class_c_g_a_l_1_1_dispatch__output__iterator.html", "class_c_g_a_l_1_1_dispatch__output__iterator" ],
      [ "Emptyset_iterator", "struct_c_g_a_l_1_1_emptyset__iterator.html", "struct_c_g_a_l_1_1_emptyset__iterator" ],
      [ "Fast", "struct_c_g_a_l_1_1_fast.html", null ],
      [ "Filter_iterator", "struct_c_g_a_l_1_1_filter__iterator.html", "struct_c_g_a_l_1_1_filter__iterator" ],
      [ "Fourtuple", "class_c_g_a_l_1_1_fourtuple.html", "class_c_g_a_l_1_1_fourtuple" ],
      [ "Get_address", "struct_c_g_a_l_1_1_get__address.html", "struct_c_g_a_l_1_1_get__address" ],
      [ "Identity", "struct_c_g_a_l_1_1_identity.html", "struct_c_g_a_l_1_1_identity" ],
      [ "In_place_list", "class_c_g_a_l_1_1_in__place__list.html", "class_c_g_a_l_1_1_in__place__list" ],
      [ "In_place_list_base", "class_c_g_a_l_1_1_in__place__list__base.html", "class_c_g_a_l_1_1_in__place__list__base" ],
      [ "Insert_iterator", "class_c_g_a_l_1_1_insert__iterator.html", "class_c_g_a_l_1_1_insert__iterator" ],
      [ "Inverse_index", "class_c_g_a_l_1_1_inverse__index.html", "class_c_g_a_l_1_1_inverse__index" ],
      [ "Iterator_range", "class_c_g_a_l_1_1_iterator__range.html", "class_c_g_a_l_1_1_iterator__range" ],
      [ "Join_input_iterator_1", "class_c_g_a_l_1_1_join__input__iterator__1.html", "class_c_g_a_l_1_1_join__input__iterator__1" ],
      [ "Join_input_iterator_2", "class_c_g_a_l_1_1_join__input__iterator__2.html", "class_c_g_a_l_1_1_join__input__iterator__2" ],
      [ "Join_input_iterator_3", "class_c_g_a_l_1_1_join__input__iterator__3.html", "class_c_g_a_l_1_1_join__input__iterator__3" ],
      [ "Location_policy", "struct_c_g_a_l_1_1_location__policy.html", null ],
      [ "Manifold_tag", "struct_c_g_a_l_1_1_manifold__tag.html", null ],
      [ "Manifold_with_boundary_tag", "struct_c_g_a_l_1_1_manifold__with__boundary__tag.html", null ],
      [ "Multiset", "class_c_g_a_l_1_1_multiset.html", "class_c_g_a_l_1_1_multiset" ],
      [ "N_step_adaptor", "class_c_g_a_l_1_1_n__step__adaptor.html", "class_c_g_a_l_1_1_n__step__adaptor" ],
      [ "Non_manifold_tag", "struct_c_g_a_l_1_1_non__manifold__tag.html", null ],
      [ "Null_functor", "struct_c_g_a_l_1_1_null__functor.html", null ],
      [ "Null_tag", "struct_c_g_a_l_1_1_null__tag.html", null ],
      [ "Object", "class_c_g_a_l_1_1_object.html", "class_c_g_a_l_1_1_object" ],
      [ "Oneset_iterator", "class_c_g_a_l_1_1_oneset__iterator.html", "class_c_g_a_l_1_1_oneset__iterator" ],
      [ "Parallel_if_available_tag", "struct_c_g_a_l_1_1_parallel__if__available__tag.html", null ],
      [ "Parallel_tag", "struct_c_g_a_l_1_1_parallel__tag.html", null ],
      [ "Project_facet", "struct_c_g_a_l_1_1_project__facet.html", "struct_c_g_a_l_1_1_project__facet" ],
      [ "Project_next", "struct_c_g_a_l_1_1_project__next.html", "struct_c_g_a_l_1_1_project__next" ],
      [ "Project_next_opposite", "struct_c_g_a_l_1_1_project__next__opposite.html", "struct_c_g_a_l_1_1_project__next__opposite" ],
      [ "Project_normal", "struct_c_g_a_l_1_1_project__normal.html", "struct_c_g_a_l_1_1_project__normal" ],
      [ "Project_opposite_prev", "struct_c_g_a_l_1_1_project__opposite__prev.html", "struct_c_g_a_l_1_1_project__opposite__prev" ],
      [ "Project_plane", "struct_c_g_a_l_1_1_project__plane.html", "struct_c_g_a_l_1_1_project__plane" ],
      [ "Project_point", "struct_c_g_a_l_1_1_project__point.html", "struct_c_g_a_l_1_1_project__point" ],
      [ "Project_prev", "struct_c_g_a_l_1_1_project__prev.html", "struct_c_g_a_l_1_1_project__prev" ],
      [ "Project_vertex", "struct_c_g_a_l_1_1_project__vertex.html", "struct_c_g_a_l_1_1_project__vertex" ],
      [ "Quadruple", "class_c_g_a_l_1_1_quadruple.html", "class_c_g_a_l_1_1_quadruple" ],
      [ "Random_access_adaptor", "class_c_g_a_l_1_1_random__access__adaptor.html", "class_c_g_a_l_1_1_random__access__adaptor" ],
      [ "Random_access_value_adaptor", "class_c_g_a_l_1_1_random__access__value__adaptor.html", "class_c_g_a_l_1_1_random__access__value__adaptor" ],
      [ "Sequential_tag", "struct_c_g_a_l_1_1_sequential__tag.html", null ],
      [ "Sixtuple", "class_c_g_a_l_1_1_sixtuple.html", "class_c_g_a_l_1_1_sixtuple" ],
      [ "Spatial_lock_grid_3", "class_c_g_a_l_1_1_spatial__lock__grid__3.html", "class_c_g_a_l_1_1_spatial__lock__grid__3" ],
      [ "Threetuple", "class_c_g_a_l_1_1_threetuple.html", "class_c_g_a_l_1_1_threetuple" ],
      [ "Triple", "class_c_g_a_l_1_1_triple.html", "class_c_g_a_l_1_1_triple" ],
      [ "Twotuple", "class_c_g_a_l_1_1_twotuple.html", "class_c_g_a_l_1_1_twotuple" ],
      [ "Uncertain", "class_c_g_a_l_1_1_uncertain.html", "class_c_g_a_l_1_1_uncertain" ],
      [ "value_type_traits", "struct_c_g_a_l_1_1value__type__traits.html", "struct_c_g_a_l_1_1value__type__traits" ],
      [ "value_type_traits< std::back_insert_iterator< Container > >", "struct_c_g_a_l_1_1value__type__traits_3_01std_1_1back__insert__iterator_3_01_container_01_4_01_4.html", "struct_c_g_a_l_1_1value__type__traits_3_01std_1_1back__insert__iterator_3_01_container_01_4_01_4" ],
      [ "value_type_traits< std::front_insert_iterator< Container > >", "struct_c_g_a_l_1_1value__type__traits_3_01std_1_1front__insert__iterator_3_01_container_01_4_01_4.html", "struct_c_g_a_l_1_1value__type__traits_3_01std_1_1front__insert__iterator_3_01_container_01_4_01_4" ],
      [ "value_type_traits< std::insert_iterator< Container > >", "struct_c_g_a_l_1_1value__type__traits_3_01std_1_1insert__iterator_3_01_container_01_4_01_4.html", "struct_c_g_a_l_1_1value__type__traits_3_01std_1_1insert__iterator_3_01_container_01_4_01_4" ]
    ] ],
    [ "Descriptor", "class_descriptor.html", null ],
    [ "Hashable", "class_hashable.html", null ],
    [ "Index", "class_index.html", null ],
    [ "ObjectWithEraseCounter", "class_object_with_erase_counter.html", "class_object_with_erase_counter" ],
    [ "ProjectionObject", "class_projection_object.html", "class_projection_object" ],
    [ "SurjectiveLockDataStructure", "class_surjective_lock_data_structure.html", "class_surjective_lock_data_structure" ]
];