var searchData=
[
  ['i_2fo_0',['I/O',['../../Arrangement_on_surface_2/group___pkg_arrangement_on_surface2_i_o.html',1,'(Global Namespace)'],['../../Surface_mesher/group___pkg_surface_mesher3_functions_i_o.html',1,'(Global Namespace)']]],
  ['i_2fo_20enums_1',['I/O Enums',['../../Stream_support/group___pkg_stream_support_enum_ref.html',1,'']]],
  ['i_2fo_20for_20a_20triangulation_203_2',['I/O for a Triangulation 3',['../../Triangulation_3/group___pkg_i_o_triangulation3.html',1,'']]],
  ['i_2fo_20for_20a_20triangulation_5fdata_5fstructure_5f3_3',['I/O for a Triangulation_data_structure_3',['../../TDS_3/group___pkg_i_o_t_d_s3.html',1,'']]],
  ['i_2fo_20functions_4',['I/O Functions',['../../Stream_support/group___i_ostream_functions.html',1,'(Global Namespace)'],['../../Isosurfacing_3/group___i_s___i_o__functions__grp.html',1,'(Global Namespace)'],['../../BGL/group___pkg_b_g_l_i_o_fct.html',1,'(Global Namespace)'],['../../Mesh_2/group___pkg_mesh2_i_o.html',1,'(Global Namespace)'],['../../Nef_3/group___pkg_nef3_i_o_functions.html',1,'(Global Namespace)'],['../../Point_set_processing_3/group___pkg_point_set_processing3_i_o.html',1,'(Global Namespace)'],['../../Polyhedron/group___pkg_polyhedron_i_o_func.html',1,'(Global Namespace)'],['../../Surface_mesh/group___pkg_surface_mesh_i_o_func.html',1,'(Global Namespace)'],['../../PMP_Mesh_repair/group___p_m_p___i_o__grp.html',1,'(Global Namespace)']]],
  ['i_2fo_20functions_20_283mf_29_5',['I/O Functions (3MF)',['../../Surface_mesh/group___pkg_surface_mesh_i_o_func3_m_f.html',1,'']]],
  ['i_2fo_20functions_20_28deprecated_29_6',['I/O Functions (Deprecated)',['../../Surface_mesh/group___pkg_surface_mesh_i_o_func_deprecated.html',1,'']]],
  ['i_2fo_20functions_20_28off_29_7',['I/O Functions (OFF)',['../../Surface_mesh/group___pkg_surface_mesh_i_o_func_o_f_f.html',1,'']]],
  ['i_2fo_20functions_20_28ply_29_8',['I/O Functions (PLY)',['../../Surface_mesh/group___pkg_surface_mesh_i_o_func_p_l_y.html',1,'']]],
  ['input_20classes_9',['Input Classes',['../../GraphicsView/group___pkg_graphics_view_input_classes.html',1,'']]],
  ['input_2foutput_10',['Input/Output',['../../Point_set_3/group___pkg_point_set3_i_o.html',1,'']]],
  ['input_2foutput_20_28las_29_11',['Input/Output (LAS)',['../../Point_set_3/group___pkg_point_set3_i_o_l_a_s.html',1,'']]],
  ['input_2foutput_20_28off_29_12',['Input/Output (OFF)',['../../Point_set_3/group___pkg_point_set3_i_o_o_f_f.html',1,'']]],
  ['input_2foutput_20_28ply_29_13',['Input/Output (PLY)',['../../Point_set_3/group___pkg_point_set3_i_o_p_l_y.html',1,'']]],
  ['input_2foutput_20_28xyz_29_14',['Input/Output (XYZ)',['../../Point_set_3/group___pkg_point_set3_i_o_x_y_z.html',1,'']]],
  ['input_2foutput_20functions_15',['Input/Output Functions',['../../Triangulation_on_hyperbolic_surface_2/group___pkg_hyperbolic_surface_triangulation2_input_output.html',1,'(Global Namespace)'],['../../Mesh_3/group___pkg_mesh3_i_o_functions.html',1,'(Global Namespace)'],['../../Periodic_3_mesh_3/group___pkg_periodic3_mesh3_i_o_functions.html',1,'(Global Namespace)'],['../../SMDS_3/group___pkg_s_m_d_s3_i_o_functions.html',1,'(Global Namespace)']]],
  ['interpolation_20functions_16',['Interpolation Functions',['../../Interpolation/group___pkg_interpolation2_interpolation.html',1,'']]],
  ['intersection_20computation_20functions_20_2d_20cgal_3a_3aintersection_28_29_17',['Intersection Computation Functions - CGAL::intersection()',['../../Kernel_23/group__intersection__grp.html',1,'']]],
  ['intersection_20functions_18',['Intersection Functions',['../../Polygon_mesh_processing/group___p_m_p__intersection__grp.html',1,'']]],
  ['intersection_20test_20functions_19',['Intersection Test Functions',['../../Convex_hull_3/group___pkg_convex_hull3_intersections.html',1,'']]],
  ['intersection_20testing_20functions_20_2d_20cgal_3a_3ado_5fintersect_28_29_20',['Intersection Testing Functions - CGAL::do_intersect()',['../../Kernel_23/group__do__intersect__grp.html',1,'']]],
  ['inverse_20distance_20weight_21',['Inverse Distance Weight',['../../Weights/group___pkg_weights_ref_inverse_distance_weights.html',1,'']]],
  ['io_20functions_20for_20cmap_22',['IO Functions for CMap',['../../Combinatorial_map/group___pkg_combinatorial_maps_ref_i_o.html',1,'']]],
  ['io_20functions_20for_20lcc_23',['IO Functions for LCC',['../../Linear_cell_complex/group___pkg_linear_cell_complex_ref_i_o.html',1,'']]],
  ['is_20pullout_20direction_24',['Is Pullout Direction',['../../Set_movable_separability_2/group__is__pullout__direction__grp.html',1,'']]],
  ['isosurfacing_20domain_20helpers_25',['Isosurfacing Domain Helpers',['../../Isosurfacing_3/group___i_s___domain__helpers__grp.html',1,'']]],
  ['isosurfacing_20domains_26',['Isosurfacing Domains',['../../Isosurfacing_3/group___i_s___domains__grp.html',1,'']]],
  ['isosurfacing_20methods_27',['Isosurfacing Methods',['../../Isosurfacing_3/group___i_s___methods__grp.html',1,'']]],
  ['item_20classes_28',['Item Classes',['../../HalfedgeDS/group___pkg_halfedge_d_s___items.html',1,'']]],
  ['iterators_20and_20circulators_29',['Iterators and Circulators',['../../BGL/group___pkg_b_g_l_iterators.html',1,'']]],
  ['iterators_20and_20iterator_2fcirculator_20adaptors_30',['Iterators and Iterator/Circulator Adaptors',['../../STL_Extension/group___s_t_l_iterators.html',1,'']]]
];
