var annotated =
[
    [ "CGAL", null, [
      [ "Approximate_min_ellipsoid_d", "class_c_g_a_l_1_1_approximate__min__ellipsoid__d.html", "class_c_g_a_l_1_1_approximate__min__ellipsoid__d" ],
      [ "Approximate_min_ellipsoid_d_traits_2", "struct_c_g_a_l_1_1_approximate__min__ellipsoid__d__traits__2.html", "struct_c_g_a_l_1_1_approximate__min__ellipsoid__d__traits__2" ],
      [ "Approximate_min_ellipsoid_d_traits_3", "struct_c_g_a_l_1_1_approximate__min__ellipsoid__d__traits__3.html", "struct_c_g_a_l_1_1_approximate__min__ellipsoid__d__traits__3" ],
      [ "Approximate_min_ellipsoid_d_traits_d", "struct_c_g_a_l_1_1_approximate__min__ellipsoid__d__traits__d.html", "struct_c_g_a_l_1_1_approximate__min__ellipsoid__d__traits__d" ],
      [ "Min_annulus_d", "class_c_g_a_l_1_1_min__annulus__d.html", "class_c_g_a_l_1_1_min__annulus__d" ],
      [ "Min_circle_2", "class_c_g_a_l_1_1_min__circle__2.html", "class_c_g_a_l_1_1_min__circle__2" ],
      [ "Min_circle_2_traits_2", "class_c_g_a_l_1_1_min__circle__2__traits__2.html", "class_c_g_a_l_1_1_min__circle__2__traits__2" ],
      [ "Min_ellipse_2", "class_c_g_a_l_1_1_min__ellipse__2.html", "class_c_g_a_l_1_1_min__ellipse__2" ],
      [ "Min_ellipse_2_traits_2", "class_c_g_a_l_1_1_min__ellipse__2__traits__2.html", "class_c_g_a_l_1_1_min__ellipse__2__traits__2" ],
      [ "Min_quadrilateral_default_traits_2", "struct_c_g_a_l_1_1_min__quadrilateral__default__traits__2.html", "struct_c_g_a_l_1_1_min__quadrilateral__default__traits__2" ],
      [ "Min_sphere_annulus_d_traits_2", "class_c_g_a_l_1_1_min__sphere__annulus__d__traits__2.html", "class_c_g_a_l_1_1_min__sphere__annulus__d__traits__2" ],
      [ "Min_sphere_annulus_d_traits_3", "class_c_g_a_l_1_1_min__sphere__annulus__d__traits__3.html", "class_c_g_a_l_1_1_min__sphere__annulus__d__traits__3" ],
      [ "Min_sphere_annulus_d_traits_d", "class_c_g_a_l_1_1_min__sphere__annulus__d__traits__d.html", "class_c_g_a_l_1_1_min__sphere__annulus__d__traits__d" ],
      [ "Min_sphere_d", "class_c_g_a_l_1_1_min__sphere__d.html", "class_c_g_a_l_1_1_min__sphere__d" ],
      [ "Min_sphere_of_points_d_traits_2", "class_c_g_a_l_1_1_min__sphere__of__points__d__traits__2.html", "class_c_g_a_l_1_1_min__sphere__of__points__d__traits__2" ],
      [ "Min_sphere_of_points_d_traits_3", "class_c_g_a_l_1_1_min__sphere__of__points__d__traits__3.html", "class_c_g_a_l_1_1_min__sphere__of__points__d__traits__3" ],
      [ "Min_sphere_of_points_d_traits_d", "class_c_g_a_l_1_1_min__sphere__of__points__d__traits__d.html", "class_c_g_a_l_1_1_min__sphere__of__points__d__traits__d" ],
      [ "Min_sphere_of_spheres_d", "class_c_g_a_l_1_1_min__sphere__of__spheres__d.html", "class_c_g_a_l_1_1_min__sphere__of__spheres__d" ],
      [ "Min_sphere_of_spheres_d_traits_2", "class_c_g_a_l_1_1_min__sphere__of__spheres__d__traits__2.html", "class_c_g_a_l_1_1_min__sphere__of__spheres__d__traits__2" ],
      [ "Min_sphere_of_spheres_d_traits_3", "class_c_g_a_l_1_1_min__sphere__of__spheres__d__traits__3.html", "class_c_g_a_l_1_1_min__sphere__of__spheres__d__traits__3" ],
      [ "Min_sphere_of_spheres_d_traits_d", "class_c_g_a_l_1_1_min__sphere__of__spheres__d__traits__d.html", "class_c_g_a_l_1_1_min__sphere__of__spheres__d__traits__d" ],
      [ "Rectangular_p_center_default_traits_2", "class_c_g_a_l_1_1_rectangular__p__center__default__traits__2.html", "class_c_g_a_l_1_1_rectangular__p__center__default__traits__2" ]
    ] ],
    [ "ApproximateMinEllipsoid_d_Traits_d", "class_approximate_min_ellipsoid__d___traits__d.html", "class_approximate_min_ellipsoid__d___traits__d" ],
    [ "Circle", "class_circle.html", "class_circle" ],
    [ "Ellipse", "class_ellipse.html", "class_ellipse" ],
    [ "MinCircle2Traits", "class_min_circle2_traits.html", "class_min_circle2_traits" ],
    [ "MinEllipse2Traits", "class_min_ellipse2_traits.html", "class_min_ellipse2_traits" ],
    [ "MinQuadrilateralTraits_2", "class_min_quadrilateral_traits__2.html", "class_min_quadrilateral_traits__2" ],
    [ "MinSphereAnnulusDTraits", "class_min_sphere_annulus_d_traits.html", "class_min_sphere_annulus_d_traits" ],
    [ "MinSphereOfSpheresTraits", "class_min_sphere_of_spheres_traits.html", "class_min_sphere_of_spheres_traits" ],
    [ "RectangularPCenterTraits_2", "class_rectangular_p_center_traits__2.html", "class_rectangular_p_center_traits__2" ]
];