var annotated =
[
    [ "CGAL", null, [
      [ "Combination_enumerator", "class_c_g_a_l_1_1_combination__enumerator.html", "class_c_g_a_l_1_1_combination__enumerator" ],
      [ "Points_on_segment_2", "class_c_g_a_l_1_1_points__on__segment__2.html", "class_c_g_a_l_1_1_points__on__segment__2" ],
      [ "Random", "class_c_g_a_l_1_1_random.html", "class_c_g_a_l_1_1_random" ],
      [ "Random_convex_set_traits_2", "struct_c_g_a_l_1_1_random__convex__set__traits__2.html", "struct_c_g_a_l_1_1_random__convex__set__traits__2" ],
      [ "Random_points_in_ball_d", "class_c_g_a_l_1_1_random__points__in__ball__d.html", "class_c_g_a_l_1_1_random__points__in__ball__d" ],
      [ "Random_points_in_cube_3", "class_c_g_a_l_1_1_random__points__in__cube__3.html", "class_c_g_a_l_1_1_random__points__in__cube__3" ],
      [ "Random_points_in_cube_d", "class_c_g_a_l_1_1_random__points__in__cube__d.html", "class_c_g_a_l_1_1_random__points__in__cube__d" ],
      [ "Random_points_in_disc_2", "class_c_g_a_l_1_1_random__points__in__disc__2.html", "class_c_g_a_l_1_1_random__points__in__disc__2" ],
      [ "Random_points_in_sphere_3", "class_c_g_a_l_1_1_random__points__in__sphere__3.html", "class_c_g_a_l_1_1_random__points__in__sphere__3" ],
      [ "Random_points_in_square_2", "class_c_g_a_l_1_1_random__points__in__square__2.html", "class_c_g_a_l_1_1_random__points__in__square__2" ],
      [ "Random_points_in_tetrahedral_mesh_3", "class_c_g_a_l_1_1_random__points__in__tetrahedral__mesh__3.html", "class_c_g_a_l_1_1_random__points__in__tetrahedral__mesh__3" ],
      [ "Random_points_in_tetrahedral_mesh_boundary_3", "class_c_g_a_l_1_1_random__points__in__tetrahedral__mesh__boundary__3.html", "class_c_g_a_l_1_1_random__points__in__tetrahedral__mesh__boundary__3" ],
      [ "Random_points_in_tetrahedron_3", "class_c_g_a_l_1_1_random__points__in__tetrahedron__3.html", "class_c_g_a_l_1_1_random__points__in__tetrahedron__3" ],
      [ "Random_points_in_triangle_2", "class_c_g_a_l_1_1_random__points__in__triangle__2.html", "class_c_g_a_l_1_1_random__points__in__triangle__2" ],
      [ "Random_points_in_triangle_3", "class_c_g_a_l_1_1_random__points__in__triangle__3.html", "class_c_g_a_l_1_1_random__points__in__triangle__3" ],
      [ "Random_points_in_triangle_mesh_2", "class_c_g_a_l_1_1_random__points__in__triangle__mesh__2.html", "class_c_g_a_l_1_1_random__points__in__triangle__mesh__2" ],
      [ "Random_points_in_triangle_mesh_3", "struct_c_g_a_l_1_1_random__points__in__triangle__mesh__3.html", "struct_c_g_a_l_1_1_random__points__in__triangle__mesh__3" ],
      [ "Random_points_in_triangles_2", "struct_c_g_a_l_1_1_random__points__in__triangles__2.html", "struct_c_g_a_l_1_1_random__points__in__triangles__2" ],
      [ "Random_points_in_triangles_3", "struct_c_g_a_l_1_1_random__points__in__triangles__3.html", "struct_c_g_a_l_1_1_random__points__in__triangles__3" ],
      [ "Random_points_on_circle_2", "class_c_g_a_l_1_1_random__points__on__circle__2.html", "class_c_g_a_l_1_1_random__points__on__circle__2" ],
      [ "Random_points_on_segment_2", "class_c_g_a_l_1_1_random__points__on__segment__2.html", "class_c_g_a_l_1_1_random__points__on__segment__2" ],
      [ "Random_points_on_segment_3", "class_c_g_a_l_1_1_random__points__on__segment__3.html", "class_c_g_a_l_1_1_random__points__on__segment__3" ],
      [ "Random_points_on_sphere_3", "class_c_g_a_l_1_1_random__points__on__sphere__3.html", "class_c_g_a_l_1_1_random__points__on__sphere__3" ],
      [ "Random_points_on_sphere_d", "class_c_g_a_l_1_1_random__points__on__sphere__d.html", "class_c_g_a_l_1_1_random__points__on__sphere__d" ],
      [ "Random_points_on_square_2", "class_c_g_a_l_1_1_random__points__on__square__2.html", "class_c_g_a_l_1_1_random__points__on__square__2" ]
    ] ],
    [ "CombinationElement", "class_combination_element.html", "class_combination_element" ],
    [ "PointGenerator", "class_point_generator.html", "class_point_generator" ],
    [ "RandomConvexHullTraits_2", "class_random_convex_hull_traits__2.html", "class_random_convex_hull_traits__2" ],
    [ "RandomConvexSetTraits_2", "class_random_convex_set_traits__2.html", "class_random_convex_set_traits__2" ],
    [ "RandomPolygonTraits_2", "class_random_polygon_traits__2.html", "class_random_polygon_traits__2" ]
];