var examples =
[
    [ "QP_solver/convex_hull_containment2.cpp", "_q_p_solver_2convex_hull_containment2_8cpp-example.html", null ],
    [ "QP_solver/convex_hull_containment_benchmarks.cpp", "_q_p_solver_2convex_hull_containment_benchmarks_8cpp-example.html", null ],
    [ "QP_solver/convex_hull_containment.cpp", "_q_p_solver_2convex_hull_containment_8cpp-example.html", null ],
    [ "QP_solver/cycling.cpp", "_q_p_solver_2cycling_8cpp-example.html", null ],
    [ "QP_solver/first_lp.cpp", "_q_p_solver_2first_lp_8cpp-example.html", null ],
    [ "QP_solver/first_lp_from_iterators.cpp", "_q_p_solver_2first_lp_from_iterators_8cpp-example.html", null ],
    [ "QP_solver/first_lp_from_mps.cpp", "_q_p_solver_2first_lp_from_mps_8cpp-example.html", null ],
    [ "QP_solver/first_nonnegative_lp.cpp", "_q_p_solver_2first_nonnegative_lp_8cpp-example.html", null ],
    [ "QP_solver/first_nonnegative_lp_from_iterators.cpp", "_q_p_solver_2first_nonnegative_lp_from_iterators_8cpp-example.html", null ],
    [ "QP_solver/first_nonnegative_lp_from_mps.cpp", "_q_p_solver_2first_nonnegative_lp_from_mps_8cpp-example.html", null ],
    [ "QP_solver/first_nonnegative_qp.cpp", "_q_p_solver_2first_nonnegative_qp_8cpp-example.html", null ],
    [ "QP_solver/first_nonnegative_qp_from_iterators.cpp", "_q_p_solver_2first_nonnegative_qp_from_iterators_8cpp-example.html", null ],
    [ "QP_solver/first_nonnegative_qp_from_mps.cpp", "_q_p_solver_2first_nonnegative_qp_from_mps_8cpp-example.html", null ],
    [ "QP_solver/first_qp_basic_constraints.cpp", "_q_p_solver_2first_qp_basic_constraints_8cpp-example.html", null ],
    [ "QP_solver/first_qp.cpp", "_q_p_solver_2first_qp_8cpp-example.html", null ],
    [ "QP_solver/first_qp_from_iterators.cpp", "_q_p_solver_2first_qp_from_iterators_8cpp-example.html", null ],
    [ "QP_solver/first_qp_from_mps.cpp", "_q_p_solver_2first_qp_from_mps_8cpp-example.html", null ],
    [ "QP_solver/important_variables.cpp", "_q_p_solver_2important_variables_8cpp-example.html", null ],
    [ "QP_solver/infeasibility_certificate.cpp", "_q_p_solver_2infeasibility_certificate_8cpp-example.html", null ],
    [ "QP_solver/invert_matrix.cpp", "_q_p_solver_2invert_matrix_8cpp-example.html", null ],
    [ "QP_solver/optimality_certificate.cpp", "_q_p_solver_2optimality_certificate_8cpp-example.html", null ],
    [ "QP_solver/print_first_lp.cpp", "_q_p_solver_2print_first_lp_8cpp-example.html", null ],
    [ "QP_solver/print_first_nonnegative_lp.cpp", "_q_p_solver_2print_first_nonnegative_lp_8cpp-example.html", null ],
    [ "QP_solver/print_first_nonnegative_qp.cpp", "_q_p_solver_2print_first_nonnegative_qp_8cpp-example.html", null ],
    [ "QP_solver/print_first_qp.cpp", "_q_p_solver_2print_first_qp_8cpp-example.html", null ],
    [ "QP_solver/solve_convex_hull_containment_lp2.h", "_q_p_solver_2solve_convex_hull_containment_lp2_8h-example.html", null ],
    [ "QP_solver/solve_convex_hull_containment_lp3.h", "_q_p_solver_2solve_convex_hull_containment_lp3_8h-example.html", null ],
    [ "QP_solver/solve_convex_hull_containment_lp.h", "_q_p_solver_2solve_convex_hull_containment_lp_8h-example.html", null ],
    [ "QP_solver/unboundedness_certificate.cpp", "_q_p_solver_2unboundedness_certificate_8cpp-example.html", null ]
];