var annotated =
[
    [ "CGAL", "namespace_c_g_a_l.html", [
      [ "Dual", "class_c_g_a_l_1_1_dual.html", "class_c_g_a_l_1_1_dual" ],
      [ "dynamic_edge_property_t", "struct_c_g_a_l_1_1dynamic__edge__property__t.html", null ],
      [ "dynamic_face_property_t", "struct_c_g_a_l_1_1dynamic__face__property__t.html", null ],
      [ "dynamic_halfedge_property_t", "struct_c_g_a_l_1_1dynamic__halfedge__property__t.html", null ],
      [ "dynamic_vertex_property_t", "struct_c_g_a_l_1_1dynamic__vertex__property__t.html", null ],
      [ "Face_around_face_circulator", "class_c_g_a_l_1_1_face__around__face__circulator.html", null ],
      [ "Face_around_face_iterator", "class_c_g_a_l_1_1_face__around__face__iterator.html", null ],
      [ "Face_around_target_circulator", "class_c_g_a_l_1_1_face__around__target__circulator.html", null ],
      [ "Face_around_target_iterator", "class_c_g_a_l_1_1_face__around__target__iterator.html", null ],
      [ "Face_filtered_graph", "struct_c_g_a_l_1_1_face__filtered__graph.html", "struct_c_g_a_l_1_1_face__filtered__graph" ],
      [ "graph_has_property", "struct_c_g_a_l_1_1graph__has__property.html", null ],
      [ "Graph_with_descriptor_with_graph", "struct_c_g_a_l_1_1_graph__with__descriptor__with__graph.html", null ],
      [ "Graph_with_descriptor_with_graph_property_map", "struct_c_g_a_l_1_1_graph__with__descriptor__with__graph__property__map.html", null ],
      [ "Halfedge_around_face_circulator", "class_c_g_a_l_1_1_halfedge__around__face__circulator.html", null ],
      [ "Halfedge_around_face_iterator", "class_c_g_a_l_1_1_halfedge__around__face__iterator.html", null ],
      [ "Halfedge_around_source_circulator", "class_c_g_a_l_1_1_halfedge__around__source__circulator.html", null ],
      [ "Halfedge_around_source_iterator", "class_c_g_a_l_1_1_halfedge__around__source__iterator.html", null ],
      [ "Halfedge_around_target_circulator", "class_c_g_a_l_1_1_halfedge__around__target__circulator.html", null ],
      [ "Halfedge_around_target_iterator", "class_c_g_a_l_1_1_halfedge__around__target__iterator.html", null ],
      [ "HalfedgeDS_face_max_base_with_id", "class_c_g_a_l_1_1_halfedge_d_s__face__max__base__with__id.html", "class_c_g_a_l_1_1_halfedge_d_s__face__max__base__with__id" ],
      [ "HalfedgeDS_halfedge_max_base_with_id", "class_c_g_a_l_1_1_halfedge_d_s__halfedge__max__base__with__id.html", "class_c_g_a_l_1_1_halfedge_d_s__halfedge__max__base__with__id" ],
      [ "HalfedgeDS_vertex_max_base_with_id", "class_c_g_a_l_1_1_halfedge_d_s__vertex__max__base__with__id.html", "class_c_g_a_l_1_1_halfedge_d_s__vertex__max__base__with__id" ],
      [ "Linear_cell_complex_bgl_min_items", "struct_c_g_a_l_1_1_linear__cell__complex__bgl__min__items.html", null ],
      [ "Linear_cell_complex_for_bgl_combinatorial_map_helper", "struct_c_g_a_l_1_1_linear__cell__complex__for__bgl__combinatorial__map__helper.html", "struct_c_g_a_l_1_1_linear__cell__complex__for__bgl__combinatorial__map__helper" ],
      [ "Polyhedron_items_with_id_3", "class_c_g_a_l_1_1_polyhedron__items__with__id__3.html", "class_c_g_a_l_1_1_polyhedron__items__with__id__3" ],
      [ "Seam_mesh", "class_c_g_a_l_1_1_seam__mesh.html", "class_c_g_a_l_1_1_seam__mesh" ],
      [ "Triangulation_face_base_with_id_2", "class_c_g_a_l_1_1_triangulation__face__base__with__id__2.html", "class_c_g_a_l_1_1_triangulation__face__base__with__id__2" ],
      [ "Triangulation_vertex_base_with_id_2", "class_c_g_a_l_1_1_triangulation__vertex__base__with__id__2.html", "class_c_g_a_l_1_1_triangulation__vertex__base__with__id__2" ],
      [ "Vertex_around_face_circulator", "class_c_g_a_l_1_1_vertex__around__face__circulator.html", null ],
      [ "Vertex_around_face_iterator", "class_c_g_a_l_1_1_vertex__around__face__iterator.html", null ],
      [ "Vertex_around_target_circulator", "class_c_g_a_l_1_1_vertex__around__target__circulator.html", null ],
      [ "Vertex_around_target_iterator", "class_c_g_a_l_1_1_vertex__around__target__iterator.html", null ]
    ] ],
    [ "EdgeListGraph", "class_edge_list_graph.html", "class_edge_list_graph" ],
    [ "FaceGraph", "class_face_graph.html", "class_face_graph" ],
    [ "FaceListGraph", "class_face_list_graph.html", "class_face_list_graph" ],
    [ "HalfedgeGraph", "class_halfedge_graph.html", "class_halfedge_graph" ],
    [ "HalfedgeListGraph", "class_halfedge_list_graph.html", "class_halfedge_list_graph" ],
    [ "MutableFaceGraph", "class_mutable_face_graph.html", "class_mutable_face_graph" ],
    [ "MutableHalfedgeGraph", "class_mutable_halfedge_graph.html", "class_mutable_halfedge_graph" ],
    [ "VertexListGraph", "class_vertex_list_graph.html", "class_vertex_list_graph" ]
];