var annotated =
[
    [ "AlgebraicStructureTraits_", "namespace_algebraic_structure_traits__.html", [
      [ "Div", "class_algebraic_structure_traits___1_1_div.html", "class_algebraic_structure_traits___1_1_div" ],
      [ "Divides", "class_algebraic_structure_traits___1_1_divides.html", "class_algebraic_structure_traits___1_1_divides" ],
      [ "DivMod", "class_algebraic_structure_traits___1_1_div_mod.html", "class_algebraic_structure_traits___1_1_div_mod" ],
      [ "Gcd", "class_algebraic_structure_traits___1_1_gcd.html", "class_algebraic_structure_traits___1_1_gcd" ],
      [ "IntegralDivision", "class_algebraic_structure_traits___1_1_integral_division.html", "class_algebraic_structure_traits___1_1_integral_division" ],
      [ "Inverse", "class_algebraic_structure_traits___1_1_inverse.html", "class_algebraic_structure_traits___1_1_inverse" ],
      [ "IsOne", "class_algebraic_structure_traits___1_1_is_one.html", "class_algebraic_structure_traits___1_1_is_one" ],
      [ "IsSquare", "class_algebraic_structure_traits___1_1_is_square.html", "class_algebraic_structure_traits___1_1_is_square" ],
      [ "IsZero", "class_algebraic_structure_traits___1_1_is_zero.html", "class_algebraic_structure_traits___1_1_is_zero" ],
      [ "KthRoot", "class_algebraic_structure_traits___1_1_kth_root.html", "class_algebraic_structure_traits___1_1_kth_root" ],
      [ "Mod", "class_algebraic_structure_traits___1_1_mod.html", "class_algebraic_structure_traits___1_1_mod" ],
      [ "RootOf", "class_algebraic_structure_traits___1_1_root_of.html", "class_algebraic_structure_traits___1_1_root_of" ],
      [ "Simplify", "class_algebraic_structure_traits___1_1_simplify.html", "class_algebraic_structure_traits___1_1_simplify" ],
      [ "Sqrt", "class_algebraic_structure_traits___1_1_sqrt.html", "class_algebraic_structure_traits___1_1_sqrt" ],
      [ "Square", "class_algebraic_structure_traits___1_1_square.html", "class_algebraic_structure_traits___1_1_square" ],
      [ "UnitPart", "class_algebraic_structure_traits___1_1_unit_part.html", "class_algebraic_structure_traits___1_1_unit_part" ]
    ] ],
    [ "CGAL", null, [
      [ "Algebraic_structure_traits", "class_c_g_a_l_1_1_algebraic__structure__traits.html", null ],
      [ "Coercion_traits", "struct_c_g_a_l_1_1_coercion__traits.html", "struct_c_g_a_l_1_1_coercion__traits" ],
      [ "Euclidean_ring_tag", "struct_c_g_a_l_1_1_euclidean__ring__tag.html", null ],
      [ "Field_tag", "struct_c_g_a_l_1_1_field__tag.html", null ],
      [ "Field_with_kth_root_tag", "struct_c_g_a_l_1_1_field__with__kth__root__tag.html", null ],
      [ "Field_with_root_of_tag", "struct_c_g_a_l_1_1_field__with__root__of__tag.html", null ],
      [ "Field_with_sqrt_tag", "struct_c_g_a_l_1_1_field__with__sqrt__tag.html", null ],
      [ "Fraction_traits", "class_c_g_a_l_1_1_fraction__traits.html", null ],
      [ "Integral_domain_tag", "struct_c_g_a_l_1_1_integral__domain__tag.html", null ],
      [ "Integral_domain_without_division_tag", "struct_c_g_a_l_1_1_integral__domain__without__division__tag.html", null ],
      [ "Real_embeddable_traits", "class_c_g_a_l_1_1_real__embeddable__traits.html", null ],
      [ "Unique_factorization_domain_tag", "struct_c_g_a_l_1_1_unique__factorization__domain__tag.html", null ]
    ] ],
    [ "FractionTraits_", "namespace_fraction_traits__.html", [
      [ "CommonFactor", "class_fraction_traits___1_1_common_factor.html", "class_fraction_traits___1_1_common_factor" ],
      [ "Compose", "class_fraction_traits___1_1_compose.html", "class_fraction_traits___1_1_compose" ],
      [ "Decompose", "class_fraction_traits___1_1_decompose.html", "class_fraction_traits___1_1_decompose" ]
    ] ],
    [ "RealEmbeddableTraits_", "namespace_real_embeddable_traits__.html", [
      [ "Abs", "class_real_embeddable_traits___1_1_abs.html", "class_real_embeddable_traits___1_1_abs" ],
      [ "Compare", "class_real_embeddable_traits___1_1_compare.html", "class_real_embeddable_traits___1_1_compare" ],
      [ "IsNegative", "class_real_embeddable_traits___1_1_is_negative.html", "class_real_embeddable_traits___1_1_is_negative" ],
      [ "IsPositive", "class_real_embeddable_traits___1_1_is_positive.html", "class_real_embeddable_traits___1_1_is_positive" ],
      [ "IsZero", "class_real_embeddable_traits___1_1_is_zero.html", "class_real_embeddable_traits___1_1_is_zero" ],
      [ "Sgn", "class_real_embeddable_traits___1_1_sgn.html", "class_real_embeddable_traits___1_1_sgn" ],
      [ "ToDouble", "class_real_embeddable_traits___1_1_to_double.html", "class_real_embeddable_traits___1_1_to_double" ],
      [ "ToInterval", "class_real_embeddable_traits___1_1_to_interval.html", "class_real_embeddable_traits___1_1_to_interval" ]
    ] ],
    [ "AlgebraicStructureTraits", "class_algebraic_structure_traits.html", "class_algebraic_structure_traits" ],
    [ "EuclideanRing", "class_euclidean_ring.html", null ],
    [ "ExplicitInteroperable", "class_explicit_interoperable.html", null ],
    [ "Field", "class_field.html", "class_field" ],
    [ "FieldNumberType", "class_field_number_type.html", null ],
    [ "FieldWithKthRoot", "class_field_with_kth_root.html", null ],
    [ "FieldWithRootOf", "class_field_with_root_of.html", null ],
    [ "FieldWithSqrt", "class_field_with_sqrt.html", null ],
    [ "Fraction", "class_fraction.html", null ],
    [ "FractionTraits", "class_fraction_traits.html", "class_fraction_traits" ],
    [ "FromDoubleConstructible", "class_from_double_constructible.html", "class_from_double_constructible" ],
    [ "FromIntConstructible", "class_from_int_constructible.html", "class_from_int_constructible" ],
    [ "ImplicitInteroperable", "class_implicit_interoperable.html", null ],
    [ "IntegralDomain", "class_integral_domain.html", null ],
    [ "IntegralDomainWithoutDivision", "class_integral_domain_without_division.html", "class_integral_domain_without_division" ],
    [ "RealEmbeddable", "class_real_embeddable.html", "class_real_embeddable" ],
    [ "RealEmbeddableTraits", "class_real_embeddable_traits.html", "class_real_embeddable_traits" ],
    [ "RingNumberType", "class_ring_number_type.html", null ],
    [ "UniqueFactorizationDomain", "class_unique_factorization_domain.html", null ]
];