var annotated =
[
    [ "CGAL", null, [
      [ "Distance_adapter", "class_c_g_a_l_1_1_distance__adapter.html", "class_c_g_a_l_1_1_distance__adapter" ],
      [ "Euclidean_distance", "class_c_g_a_l_1_1_euclidean__distance.html", "class_c_g_a_l_1_1_euclidean__distance" ],
      [ "Euclidean_distance_sphere_point", "class_c_g_a_l_1_1_euclidean__distance__sphere__point.html", "class_c_g_a_l_1_1_euclidean__distance__sphere__point" ],
      [ "Fair", "class_c_g_a_l_1_1_fair.html", "class_c_g_a_l_1_1_fair" ],
      [ "Fuzzy_iso_box", "class_c_g_a_l_1_1_fuzzy__iso__box.html", "class_c_g_a_l_1_1_fuzzy__iso__box" ],
      [ "Fuzzy_sphere", "class_c_g_a_l_1_1_fuzzy__sphere.html", "class_c_g_a_l_1_1_fuzzy__sphere" ],
      [ "Incremental_neighbor_search", "class_c_g_a_l_1_1_incremental__neighbor__search.html", "class_c_g_a_l_1_1_incremental__neighbor__search" ],
      [ "K_neighbor_search", "class_c_g_a_l_1_1_k__neighbor__search.html", "class_c_g_a_l_1_1_k__neighbor__search" ],
      [ "Kd_tree", "class_c_g_a_l_1_1_kd__tree.html", "class_c_g_a_l_1_1_kd__tree" ],
      [ "Kd_tree_internal_node", "class_c_g_a_l_1_1_kd__tree__internal__node.html", "class_c_g_a_l_1_1_kd__tree__internal__node" ],
      [ "Kd_tree_leaf_node", "class_c_g_a_l_1_1_kd__tree__leaf__node.html", "class_c_g_a_l_1_1_kd__tree__leaf__node" ],
      [ "Kd_tree_node", "class_c_g_a_l_1_1_kd__tree__node.html", "class_c_g_a_l_1_1_kd__tree__node" ],
      [ "Kd_tree_rectangle", "class_c_g_a_l_1_1_kd__tree__rectangle.html", "class_c_g_a_l_1_1_kd__tree__rectangle" ],
      [ "Manhattan_distance_iso_box_point", "class_c_g_a_l_1_1_manhattan__distance__iso__box__point.html", "class_c_g_a_l_1_1_manhattan__distance__iso__box__point" ],
      [ "Median_of_max_spread", "class_c_g_a_l_1_1_median__of__max__spread.html", "class_c_g_a_l_1_1_median__of__max__spread" ],
      [ "Median_of_rectangle", "class_c_g_a_l_1_1_median__of__rectangle.html", "class_c_g_a_l_1_1_median__of__rectangle" ],
      [ "Midpoint_of_max_spread", "class_c_g_a_l_1_1_midpoint__of__max__spread.html", "class_c_g_a_l_1_1_midpoint__of__max__spread" ],
      [ "Midpoint_of_rectangle", "class_c_g_a_l_1_1_midpoint__of__rectangle.html", "class_c_g_a_l_1_1_midpoint__of__rectangle" ],
      [ "Orthogonal_incremental_neighbor_search", "class_c_g_a_l_1_1_orthogonal__incremental__neighbor__search.html", "class_c_g_a_l_1_1_orthogonal__incremental__neighbor__search" ],
      [ "Orthogonal_k_neighbor_search", "class_c_g_a_l_1_1_orthogonal__k__neighbor__search.html", "class_c_g_a_l_1_1_orthogonal__k__neighbor__search" ],
      [ "Plane_separator", "class_c_g_a_l_1_1_plane__separator.html", "class_c_g_a_l_1_1_plane__separator" ],
      [ "Point_container", "class_c_g_a_l_1_1_point__container.html", "class_c_g_a_l_1_1_point__container" ],
      [ "Search_traits", "class_c_g_a_l_1_1_search__traits.html", "class_c_g_a_l_1_1_search__traits" ],
      [ "Search_traits_2", "class_c_g_a_l_1_1_search__traits__2.html", "class_c_g_a_l_1_1_search__traits__2" ],
      [ "Search_traits_3", "class_c_g_a_l_1_1_search__traits__3.html", "class_c_g_a_l_1_1_search__traits__3" ],
      [ "Search_traits_adapter", "class_c_g_a_l_1_1_search__traits__adapter.html", "class_c_g_a_l_1_1_search__traits__adapter" ],
      [ "Search_traits_d", "class_c_g_a_l_1_1_search__traits__d.html", "class_c_g_a_l_1_1_search__traits__d" ],
      [ "Sliding_fair", "class_c_g_a_l_1_1_sliding__fair.html", "class_c_g_a_l_1_1_sliding__fair" ],
      [ "Sliding_midpoint", "class_c_g_a_l_1_1_sliding__midpoint.html", "class_c_g_a_l_1_1_sliding__midpoint" ],
      [ "Weighted_Minkowski_distance", "class_c_g_a_l_1_1_weighted___minkowski__distance.html", "class_c_g_a_l_1_1_weighted___minkowski__distance" ]
    ] ],
    [ "FuzzyQueryItem", "class_fuzzy_query_item.html", "class_fuzzy_query_item" ],
    [ "GeneralDistance", "class_general_distance.html", "class_general_distance" ],
    [ "OrthogonalDistance", "class_orthogonal_distance.html", "class_orthogonal_distance" ],
    [ "RangeSearchTraits", "class_range_search_traits.html", "class_range_search_traits" ],
    [ "SearchGeomTraits_2", "class_search_geom_traits__2.html", "class_search_geom_traits__2" ],
    [ "SearchGeomTraits_3", "class_search_geom_traits__3.html", "class_search_geom_traits__3" ],
    [ "SearchTraits", "class_search_traits.html", "class_search_traits" ],
    [ "SpatialSeparator", "class_spatial_separator.html", "class_spatial_separator" ],
    [ "SpatialTree", "class_spatial_tree.html", "class_spatial_tree" ],
    [ "Splitter", "class_splitter.html", "class_splitter" ]
];